services:


  sender:
    build:
      context: .
      dockerfile: SignalSender/Dockerfile
    container_name: sender
    depends_on:
      - receiver
    ports:
      - "4000"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"


  man:
    build:
      context: .
      dockerfile: TheManInTheMiddle/Dockerfile
    container_name: TheManInTheMiddle
    network_mode: "service:receiver" #<- this is because the intercepter pkg needs to be in the same namespace as one of the other continers (for some reason)
    depends_on:
        - receiver

    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    # cap_add:
    #   - NET_RAW
    #   - NET_ADMIN
    

  receiver:
    build: 
      context: .
      dockerfile: SignalReceiver/Dockerfile
    container_name: receiver
    ports:
      - "5000"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
  

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: "service:receiver"
    depends_on:
      - receiver
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./rules:/etc/suricata/rules
      - ./suricata-logs:/var/log/suricata
    command: >
      -i eth0
      -l /var/log/suricata
      -S /etc/suricata/rules/local.rules
      
  evebox:
    image: jasonish/evebox:latest
    container_name: evebox
    depends_on:
      - suricata
    ports:
      - "5636:5636"
    volumes:
      - ./suricata-logs:/var/log/suricata:ro
      - ./evebox-data:/var/lib/evebox
    command: >
      evebox server
      --host 0.0.0.0
      --port 5636
      --sqlite /var/log/suricata/eve.json