services:
  receiver:
    build: 
      context: .
      dockerfile: SignalReceiver/Dockerfile
    container_name: receiver
    ports:
      - "5000:5000"

  sender:
    build:
      context: .
      dockerfile: SignalSender/Dockerfile
    container_name: sender
    depends_on:
      - receiver